apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: weavescope
    weavescope-component: weavescope-iowait-plugin
    name: cortex-agent-retriever
  name: weavescope-iowait-plugin
spec:
  template:
    metadata:
      labels:
        app: weavescope
        weavescope-component: weavescope-iowait-plugin
    spec:
      hostPID: true
      containers:
        - name: weavescope-iowait-plugin
          image: weaveworksplugins/scope-iops:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
          - name: scope-plugins
            mountPath: /var/run/scope/plugins
          env:
          - name: CORTEXAGENT
            value: "http://cortex-agent-service.maya-system.svc.cluster.local:80/api/v1/query?query="
      volumes:
      - name: scope-plugins
        hostPath:
          path: /var/run/scope/plugins

